"""
Export utilities: CSV report generation.
"""

import csv
import io
from models.schemas import AnalysisResponse


def generate_csv_report(result: AnalysisResponse) -> str:
    """Generate a CSV string from an AnalysisResponse."""
    ministry = result.ministry_type or "schools"
    if ministry == "housing":
        return _generate_housing_csv(result)
    if ministry == "elder_care":
        return _generate_elder_care_csv(result)
    return _generate_schools_csv(result)


# ---------------------------------------------------------------------------
# Schools
# ---------------------------------------------------------------------------

def _generate_schools_csv(result: AnalysisResponse) -> str:
    output = io.StringIO()
    w = csv.writer(output)

    w.writerow(["Catholic School Sustainability & Viability Analysis"])
    w.writerow(["Generated by Ministry Feasibility Tool"])
    w.writerow([])

    _write_summary(w, result)

    w.writerow(["SUSTAINABILITY SCORE BREAKDOWN"])
    w.writerow(["Metric", "Score (0-100)", "Rating", "Weight", "Description"])
    for metric in [
        result.feasibility_score.market_size,
        result.feasibility_score.income,
        result.feasibility_score.competition,
        result.feasibility_score.family_density,
    ]:
        if metric:
            w.writerow([metric.label, metric.score, metric.rating.title(), f"{metric.weight}%", metric.description])
    w.writerow([])

    d = result.demographics
    w.writerow(["DEMOGRAPHIC DATA"])
    w.writerow(["Metric", "Value", "Notes"])
    w.writerow(["Total Population", f"{d.total_population:,}" if d.total_population else "N/A", "ACS 5-year estimate"])
    w.writerow(["Population Under 18", f"{d.population_under_18:,}" if d.population_under_18 else "N/A", ""])
    _age_range = {"k5": "5–11", "k8": "5–14", "high_school": "14–17", "k12": "5–17"}
    age_label = _age_range.get(result.grade_level, "school-age")
    w.writerow([f"School-Age Population (ages {age_label})", f"{d.school_age_population:,}" if d.school_age_population else "N/A", "Grade-level scoped"])
    w.writerow(["Estimated Catholic % of Population", f"{d.estimated_catholic_pct}%" if d.estimated_catholic_pct else "N/A", "CARA state-level estimate"])
    w.writerow(["Est. Catholic School-Age Children", f"{d.estimated_catholic_school_age:,}" if d.estimated_catholic_school_age else "N/A", "School-age pop × Catholic %"])
    w.writerow(["Median Household Income", f"${d.median_household_income:,}" if d.median_household_income else "N/A", ""])
    w.writerow(["Total Households", f"{d.total_households:,}" if d.total_households else "N/A", ""])
    w.writerow(["Families with Children Under 18", f"{d.families_with_children:,}" if d.families_with_children else "N/A", ""])
    w.writerow(["Owner-Occupied Housing", f"{d.owner_occupied_pct}%" if d.owner_occupied_pct is not None else "N/A", "Proxy for community stability"])
    w.writerow([])

    catchment_label = _catchment_label(result)
    w.writerow(["COMPETITOR PRIVATE SCHOOLS"])
    w.writerow([f"Total private schools within {catchment_label}: {result.total_private_school_count}"])
    w.writerow([f"Catholic schools within {catchment_label}: {result.catholic_school_count}"])
    w.writerow([])
    if result.competitor_schools:
        w.writerow(["School Name", "Affiliation", "Distance (miles)", "City", "Enrollment", "Latitude", "Longitude"])
        for s in result.competitor_schools:
            w.writerow([s.name, s.affiliation, s.distance_miles, s.city or "", s.enrollment or "N/A", s.lat, s.lon])
    else:
        w.writerow(["No competitor school data available."])
    w.writerow([])

    _write_trend(w, result)
    _write_data_notes(w, result)
    _write_stage2(w, result)
    _write_phase3_sections(w, result)
    return output.getvalue()


# ---------------------------------------------------------------------------
# Housing
# ---------------------------------------------------------------------------

def _generate_housing_csv(result: AnalysisResponse) -> str:
    output = io.StringIO()
    w = csv.writer(output)

    w.writerow(["Affordable Housing Market Feasibility Analysis"])
    w.writerow(["Generated by Ministry Feasibility Tool"])
    w.writerow([])

    _write_summary(w, result)

    w.writerow(["MARKET SCORE BREAKDOWN"])
    w.writerow(["Metric", "Score (0-100)", "Rating", "Weight", "Description"])
    for metric in [
        result.feasibility_score.market_size,
        result.feasibility_score.income,
        result.feasibility_score.competition,
        result.feasibility_score.family_density,
    ]:
        if metric:
            w.writerow([metric.label, metric.score, metric.rating.title(), f"{metric.weight}%", metric.description])
    w.writerow([])

    d = result.demographics
    w.writerow(["DEMOGRAPHIC DATA"])
    w.writerow(["Metric", "Value", "Notes"])
    w.writerow(["Total Population", f"{d.total_population:,}" if d.total_population else "N/A", "ACS 5-year estimate"])
    w.writerow(["Total Households", f"{d.total_households:,}" if d.total_households else "N/A", ""])
    w.writerow(["Median Household Income", f"${d.median_household_income:,}" if d.median_household_income else "N/A", ""])
    w.writerow(["Cost-Burdened Renter Households", f"{d.ministry_target_population:,}" if d.ministry_target_population else "N/A", "Households paying >30% income on rent"])
    w.writerow(["HUD Tenant Households (Joined)", f"{d.hud_tenant_households:,}" if d.hud_tenant_households else "N/A", "Tenant aggregates joined by exact HUD_ID or tract keys"])
    w.writerow(["QCT-Designated Nearby Projects", f"{d.qct_designated_projects:,}" if d.qct_designated_projects else "0", "HUD QCT annual designations"])
    w.writerow(["DDA-Designated Nearby Projects", f"{d.dda_designated_projects:,}" if d.dda_designated_projects else "0", "HUD DDA annual designations"])
    w.writerow([])

    catchment_label = _catchment_label(result)
    w.writerow(["NEARBY LIHTC AFFORDABLE HOUSING PROJECTS"])
    w.writerow([f"LIHTC projects within {catchment_label}: {result.total_private_school_count}"])
    w.writerow([])
    if result.competitor_schools:
        w.writerow(["Project Name", "Distance (miles)", "City", "Low-Income Units", "HUD QCT", "HUD DDA", "Latitude", "Longitude"])
        for p in result.competitor_schools:
            designation_flags = (p.affiliation or "").upper()
            w.writerow([
                p.name,
                p.distance_miles,
                p.city or "",
                p.enrollment or "N/A",
                "Yes" if "QCT" in designation_flags else "No",
                "Yes" if "DDA" in designation_flags else "No",
                p.lat,
                p.lon,
            ])
    else:
        w.writerow(["No LIHTC project data available. Ensure hud_lihtc_projects.csv is present in the data directory."])
    w.writerow([])

    _write_data_notes(w, result)
    _write_stage2(w, result)
    _write_phase3_sections(w, result)
    return output.getvalue()


# ---------------------------------------------------------------------------
# Elder Care
# ---------------------------------------------------------------------------

def _generate_elder_care_csv(result: AnalysisResponse) -> str:
    output = io.StringIO()
    w = csv.writer(output)

    w.writerow(["Elder Care Market Feasibility Analysis"])
    w.writerow(["Generated by Ministry Feasibility Tool"])
    w.writerow([])

    _write_summary(w, result)

    w.writerow(["MARKET SCORE BREAKDOWN"])
    w.writerow(["Metric", "Score (0-100)", "Rating", "Weight", "Description"])
    for metric in [
        result.feasibility_score.market_size,
        result.feasibility_score.income,
        result.feasibility_score.competition,
        result.feasibility_score.family_density,
        result.feasibility_score.occupancy,
        result.feasibility_score.workforce,
    ]:
        if metric:
            w.writerow([metric.label, metric.score, metric.rating.title(), f"{metric.weight}%", metric.description])
    w.writerow([])

    d = result.demographics
    w.writerow(["DEMOGRAPHIC DATA"])
    w.writerow(["Metric", "Value", "Notes"])
    w.writerow(["Total Population", f"{d.total_population:,}" if d.total_population else "N/A", "ACS 5-year estimate"])
    w.writerow(["Median Household Income", f"${d.median_household_income:,}" if d.median_household_income else "N/A", ""])
    w.writerow(["Total Households", f"{d.total_households:,}" if d.total_households else "N/A", ""])
    w.writerow(["Seniors 65+", f"{d.seniors_65_plus:,}" if d.seniors_65_plus else "N/A", ""])
    w.writerow(["Target Senior Population", f"{d.ministry_target_population:,}" if d.ministry_target_population else "N/A", "75+ or vulnerable seniors depending on mode"])
    w.writerow(["Projected Seniors (5-year)", f"{d.seniors_projected_5yr:,}" if d.seniors_projected_5yr else "N/A", "Cohort-survival projection"])
    w.writerow(["Projected Seniors (10-year)", f"{d.seniors_projected_10yr:,}" if d.seniors_projected_10yr else "N/A", "Cohort-survival projection"])
    w.writerow([])

    catchment_label = _catchment_label(result)
    w.writerow(["NEARBY ELDER CARE FACILITIES"])
    w.writerow([f"Facilities within {catchment_label}: {result.total_private_school_count}"])
    w.writerow([])
    if result.competitor_schools:
        w.writerow(["Facility Name", "Affiliation", "Distance (miles)", "City", "Certified Beds", "Occupancy %", "MDS Rating", "Care Level", "Latitude", "Longitude"])
        for f in result.competitor_schools:
            w.writerow([
                f.name,
                f.affiliation,
                f.distance_miles,
                f.city or "",
                f.enrollment or "N/A",
                f"{f.occupancy_pct:.1f}%" if f.occupancy_pct is not None else "N/A",
                f.mds_overall_rating or "N/A",
                f.grade_level or "",
                f.lat,
                f.lon,
            ])
    else:
        w.writerow(["No elder care facility data available."])
    w.writerow([])

    _write_data_notes(w, result)
    _write_stage2(w, result)
    _write_phase3_sections(w, result)
    return output.getvalue()


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _catchment_label(result: AnalysisResponse) -> str:
    if result.catchment_type == "isochrone":
        return f"{result.catchment_minutes}-minute drive catchment"
    return f"{result.radius_miles}-mile radius"


def _write_summary(w, result: AnalysisResponse) -> None:
    ministry_labels = {
        "schools": "School / Institution Name",
        "housing": "Project Name",
        "elder_care": "Facility / Project Name",
    }
    name_label = ministry_labels.get(result.ministry_type or "schools", "Project Name")
    w.writerow(["ANALYSIS SUMMARY"])
    w.writerow([name_label, result.school_name])
    w.writerow(["Address Analyzed", result.analysis_address])
    w.writerow(["County", result.county_name])
    w.writerow(["State", result.state_name])
    if result.catchment_type == "isochrone":
        w.writerow(["Catchment", f"{result.catchment_minutes}-minute drive (road-network isochrone)"])
        w.writerow(["Effective Bounding Radius (miles)", result.radius_miles])
    else:
        w.writerow(["Catchment", f"{result.radius_miles}-mile radius"])
    w.writerow(["Overall Feasibility Score", f"{result.feasibility_score.overall}/100"])
    w.writerow(["Recommendation", result.recommendation])
    w.writerow([])


def _write_trend(w, result: AnalysisResponse) -> None:
    if not result.trend:
        return
    t = result.trend
    w.writerow(["DEMOGRAPHIC TREND (2017 → 2022, county-level)"])
    w.writerow(["Period", t.period])
    w.writerow(["Overall Trend", t.trend_label])
    w.writerow(["School-Age Population Change", f"{t.school_age_pop_pct:+.1f}%" if t.school_age_pop_pct is not None else "N/A"])
    w.writerow(["Median Income Change (real)", f"{t.income_real_pct:+.1f}%" if t.income_real_pct is not None else "N/A", "Adjusted ~19% for 2017→2022 CPI"])
    w.writerow(["Families with Children Change", f"{t.families_pct:+.1f}%" if t.families_pct is not None else "N/A"])
    w.writerow([])


def _write_data_notes(w, result: AnalysisResponse) -> None:
    w.writerow(["DATA NOTES"])
    for note in result.data_notes:
        w.writerow([note])


def _write_stage2(w, result: AnalysisResponse) -> None:
    stage2 = result.feasibility_score.stage2
    if not stage2 or not stage2.components:
        return
    w.writerow([])
    w.writerow(["STAGE 2 OPERATING KPI DATASET"])
    w.writerow(["project_name", "metric_key", "metric_label", "score_0_100", "weight_pct", "readiness", "schema_version", "formula_version", "computed_at_utc"])
    for c in stage2.components:
        w.writerow([
            result.school_name,
            c.key,
            c.label,
            "" if c.score is None else c.score,
            c.weight,
            stage2.readiness,
            stage2.schema_version,
            stage2.formula_version,
            stage2.computed_at_utc or "",
        ])


def _write_phase3_sections(w, result: AnalysisResponse) -> None:
    if result.data_freshness:
        w.writerow([])
        w.writerow(["DATA FRESHNESS"])
        w.writerow(["Mode", result.data_freshness.mode])
        w.writerow(["Generated (UTC)", result.data_freshness.generated_at_utc])
        w.writerow(["Source", "Last Refreshed UTC", "Age (hours)", "Status", "Notes"])
        for src in result.data_freshness.sources:
            w.writerow([
                src.source_label,
                src.last_refreshed_utc or "N/A",
                src.freshness_hours if src.freshness_hours is not None else "N/A",
                src.status,
                src.notes or "",
            ])

    if result.benchmark_narrative:
        b = result.benchmark_narrative
        w.writerow([])
        w.writerow(["REGIONAL BENCHMARK NARRATIVE"])
        w.writerow(["Peer Cohort", b.peer_cohort])
        w.writerow(["In-State Percentile", b.in_state_percentile if b.in_state_percentile is not None else "N/A"])
        w.writerow(["National Percentile", b.national_percentile if b.national_percentile is not None else "N/A"])
        w.writerow(["Summary", b.narrative_summary])
        for m in b.nearest_comparable_markets:
            w.writerow(["Comparable", m])

    if result.board_report_pack:
        pack = result.board_report_pack
        w.writerow([])
        w.writerow(["BOARD-READY REPORT PACK"])
        w.writerow(["Executive Summary", pack.executive_summary])
        for risk in pack.key_risks:
            w.writerow(["Risk", risk])
        for opt in pack.strategic_options:
            w.writerow(["Option", opt])
        for action in pack.immediate_next_actions:
            w.writerow(["Next Action", action])
        for action in pack.action_roadmap.months_12:
            w.writerow(["Roadmap 12 Months", action])
        for action in pack.action_roadmap.months_24:
            w.writerow(["Roadmap 24 Months", action])
        for action in pack.action_roadmap.months_36:
            w.writerow(["Roadmap 36 Months", action])
        for assumption in pack.methodology_assumptions:
            w.writerow(["Methodology", assumption])
        for note in pack.confidence_notes:
            w.writerow(["Confidence Note", note])
